### ISSUE TITLE
Build Failed : Could not find property 'SB_RELEASE_STORE_FILE'  

### ISSUE THREAD

**Issue by prashanth726** [scrollback/io.scrollback.neighborhoods#13]
FAILURE: Build failed with an exception.
- Where:
  Build file 'E:\Node\React\Scrollback\HeyNeighbour\android\app\build.gradle' line
  : 119
- What went wrong:
  A problem occurred evaluating project ':app'.
  
  > Could not find property 'SB_RELEASE_STORE_FILE' on SigningConfig_Decorated{nam
  > e=release, storeFile=null, storePassword=null, keyAlias=null, keyPassword=null,
  > storeType=null}.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

Total time: 33.324 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by prashanth726** [comment]
I think you should remove signingConfigs from gradle file in this OpenSource version of the Project ..

**Comment by satya164** [comment]
@itsPR You can add custom keys in `~/.gradle/gradle.properties`. Like,

```
SB_RELEASE_STORE_FILE=scrollback.keystore
SB_RELEASE_STORE_PASSWORD=******
SB_RELEASE_KEY_ALIAS=******
SB_RELEASE_KEY_PASSWORD=******
```

Moving the signing config from the repo will be very much inconvenient. Also if someone wants to build the APK, it's simple to add the configs.
